{% set version = '0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dt
  version: {{ version|replace("-", "_") }}

source:
  fn: DT_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/DT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DT/DT_{{ version }}.tar.gz
  sha256: 3daa96b819ca54e5fbc2c7d78cb3637982a2d44be58cea0683663b71cfc7fa19

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-crosstalk
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-magrittr
  run:
    - r-base
    - r-crosstalk
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-magrittr

test:
  commands:
    - $R -e "library('DT')"           # [not win]
    - "\"%R%\" -e \"library('DT')\""  # [win]

about:
  home: https://rstudio.github.io/DT
  license: GPL-3
  summary: Data objects in R can be rendered as HTML tables using the JavaScript library 'DataTables'
    (typically via R Markdown or Shiny). The 'DataTables' library has been included
    in this R package. The package name 'DT' is an abbreviation of 'DataTables'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
