appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: VrokfGxO/qXoDDz1PQjDN5nfeW6I6ifb72g7ftXW+8fNhnxgI83xscR0+4Qjfs7ELJcQOBysBMlwYTKVNJ9OgMf8wiqW+I/u0trlvLzSHvpr7xL9k3V2v3KvygWGM2CoWNisShfH7r8BpmPeOGPvmd9iPR0nAkC8ohlKA7HrW817XbmVOGPciymedMC6QrwUtwp2vJZKvBl76jYYCYD+MBFEEMFqSzQnlrsW4z/MbFHGHRQXC3HnJSmoE6rPyGsA569MQ8u9KwNLsiRc0X3i1ulTn+5ftyyxBCsOF5tbm+q9npsimxWC8f1Q/tls9TdAp7g4TYSNKJHLMTdutXEieTJcNZB3+/bMKvDnNNyryNeSRlWikIONVDGhwNlV5hD6vJjU9TEOjbl36kQ6Hm0pzUgDk1Swehm0nEi0gEkxWh6wJIDTfuwPIZM8xoRtN0G4p88QVesFYWyP+dvKz+8nds2oEcvRt/Ny8c0DOVjv1B32iuJ150EJTQtCutgdYOd7Msvl0uTqHW2rT7dGzLBP2CkPZ/I3El0ybD630xIJ45teqMdjqVYnVpqQmrkqNlqQBo4eoqp8T06k/wVDZmq4VQMx+ywzeVPBD96BHFuZP4PSirg0MNIl+RsMk6sAqIm1cc2hLPNa8Di4ZPpEMcBCGNE1vJhZPmq9gtt8GIcvpM0=
